-- ─────────────────────────────────────────────────────────────
-- YieldMind — Migration 001: Core Schema
-- Run via: supabase db push
-- ─────────────────────────────────────────────────────────────

-- Enable UUID generation
create extension if not exists "pgcrypto";

-- ── ENUM TYPES ─────────────────────────────────────────────────────────────

create type asset_id as enum ('USDY', 'mETH', 'USDe', 'fBTC');
create type risk_level as enum ('LOW', 'MED', 'HIGH');
create type decision_type as enum ('REBALANCE', 'YIELD', 'RISK', 'ALERT', 'INFO');
create type decision_status as enum ('pending', 'confirmed', 'failed', 'skipped');
create type alert_severity as enum ('LOW', 'MED', 'HIGH', 'CRITICAL');

-- ── AGENTS ─────────────────────────────────────────────────────────────────
-- One row per wallet. Links to ERC-8004 NFT once minted.

create table agents (
  id                uuid primary key default gen_random_uuid(),
  wallet_address    text not null unique,
  nft_token_id      text,                        -- ERC-8004 token ID, set after mint
  name              text not null default 'YieldMind Agent',
  avatar_url        text,
  total_value_usd   numeric(20, 4) not null default 0,
  weighted_apy      numeric(8, 4) not null default 0,
  decisions_count   integer not null default 0,
  created_at        timestamptz not null default now(),
  updated_at        timestamptz not null default now()
);

-- ── POSITIONS ──────────────────────────────────────────────────────────────
-- Per-asset holdings for each agent

create table positions (
  id                    uuid primary key default gen_random_uuid(),
  agent_id              uuid not null references agents(id) on delete cascade,
  asset_id              asset_id not null,
  balance               numeric(30, 8) not null default 0,
  value_usd             numeric(20, 4) not null default 0,
  allocation_pct        numeric(6, 4) not null default 0,   -- actual %
  target_allocation_pct numeric(6, 4) not null default 0,   -- AI target %
  updated_at            timestamptz not null default now(),
  unique(agent_id, asset_id)
);

-- ── AGENT DECISIONS ────────────────────────────────────────────────────────
-- Every AI decision — on-chain or off. Core audit trail.

create table agent_decisions (
  id              uuid primary key default gen_random_uuid(),
  agent_id        uuid not null references agents(id) on delete cascade,
  type            decision_type not null,
  reasoning       text not null,               -- AI-generated explanation
  action_taken    text,                        -- human-readable action summary
  tx_hash         text,                        -- Mantle tx hash if on-chain
  status          decision_status not null default 'pending',
  asset_id        asset_id,                    -- asset affected (if any)
  value_delta_usd numeric(20, 4),              -- $ change from this decision
  apy_delta       numeric(8, 4),               -- APY change from this decision
  created_at      timestamptz not null default now()
);

-- ── YIELD SNAPSHOTS ────────────────────────────────────────────────────────
-- Historical APY + price per asset, polled by agent

create table yield_snapshots (
  id          uuid primary key default gen_random_uuid(),
  asset_id    asset_id not null,
  apy         numeric(8, 4) not null,
  price_usd   numeric(20, 8) not null,
  tvl_usd     numeric(30, 4),
  source      text not null default 'bybit',
  timestamp   timestamptz not null default now()
);

-- ── RISK ALERTS ────────────────────────────────────────────────────────────
-- Alerts generated by AI risk engine

create table risk_alerts (
  id           uuid primary key default gen_random_uuid(),
  agent_id     uuid not null references agents(id) on delete cascade,
  asset_id     asset_id,
  severity     alert_severity not null,
  title        text not null,
  message      text not null,
  resolved     boolean not null default false,
  resolved_at  timestamptz,
  created_at   timestamptz not null default now()
);

-- ─────────────────────────────────────────────────────────────
-- INDEXES
-- ─────────────────────────────────────────────────────────────

create index idx_positions_agent_id on positions(agent_id);
create index idx_decisions_agent_id on agent_decisions(agent_id);
create index idx_decisions_created_at on agent_decisions(created_at desc);
create index idx_decisions_status on agent_decisions(status);
create index idx_yield_snapshots_asset_timestamp on yield_snapshots(asset_id, timestamp desc);
create index idx_risk_alerts_agent_id on risk_alerts(agent_id);
create index idx_risk_alerts_resolved on risk_alerts(resolved);

-- ─────────────────────────────────────────────────────────────
-- UPDATED_AT TRIGGER
-- ─────────────────────────────────────────────────────────────

create or replace function update_updated_at()
returns trigger as $$
begin
  new.updated_at = now();
  return new;
end;
$$ language plpgsql;

create trigger agents_updated_at
  before update on agents
  for each row execute function update_updated_at();

create trigger positions_updated_at
  before update on positions
  for each row execute function update_updated_at();

-- ─────────────────────────────────────────────────────────────
-- ROW LEVEL SECURITY
-- ─────────────────────────────────────────────────────────────

alter table agents enable row level security;
alter table positions enable row level security;
alter table agent_decisions enable row level security;
alter table yield_snapshots enable row level security;
alter table risk_alerts enable row level security;

-- yield_snapshots are public (read-only for all)
create policy "yield_snapshots_public_read"
  on yield_snapshots for select using (true);

-- Agents can only read/write their own data
-- (wallet_address matched against auth.jwt() claim in production)
-- For hackathon: service role bypasses RLS for agent writes

create policy "agents_select_own"
  on agents for select using (true);

create policy "positions_select_own"
  on positions for select using (true);

create policy "decisions_select_own"
  on agent_decisions for select using (true);

create policy "alerts_select_own"
  on risk_alerts for select using (true);
